[borders-plus-plus]
description ="A plugin to add more borders to windows."
version = "1.0"
authors = ["Vaxry"]

[borders-plus-plus.build]
output = "borders-plus-plus/borders-plus-plus.so"
steps = [
    "make -C borders-plus-plus all",
]


[hyprbars]
description = "A plugin to add title bars to windows"
version = "1.0"
authors = ["Vaxry"]

[hyprbars.build]
output = "hyprbars/hyprbars.so"
steps = [
    "make -C hyprbars all",
]
